# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=2083, null=True)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('remoteHost', models.CharField(max_length=150, null=True)),
                ('remoteIP', models.CharField(max_length=150, null=True)),
                ('userAgent', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=1000, null=True)),
                ('interaction', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
