# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170907_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='campaigns.Photo'),
        ),
    ]
