# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170912_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='language',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
