# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('targeturl', models.CharField(max_length=2083)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurDeleteHash', models.CharField(max_length=2083)),
                ('imgurId', models.CharField(max_length=2083)),
                ('imgurLink', models.CharField(max_length=2083)),
                ('on', models.BooleanField(default=True)),
                ('billboards', models.ManyToManyField(to='campaigns.Billboard')),
            ],
        ),
    ]
