# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company'),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='billboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Billboard'),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company'),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Photo'),
        ),
        migrations.AddField(
            model_name='billboard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='directory.Company'),
        ),
        migrations.AddField(
            model_name='billboard',
            name='groups',
            field=models.ManyToManyField(blank=True, to='directory.Group'),
        ),
    ]
