# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_user_timezone'),
        ('campaigns', '0002_auto_20170907_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='billboards',
        ),
        migrations.AlterField(
            model_name='billboard',
            name='groups',
            field=models.ManyToManyField(blank=True, to='directory.Group'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='billboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Billboard'),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company'),
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Photo'),
        ),
    ]
