# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20170912_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='on',
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
