# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20170912_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningBillboardMedia',
            fields=[
                ('billboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.Billboard')),
                ('billboardMedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.BillboardMedia')),
            ],
            bases=('campaigns.billboard',),
        ),
        migrations.AddField(
            model_name='billboard',
            name='ABSample',
            field=models.IntegerField(default=100),
        ),
    ]
