# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20170916_0743'),
        ('campaigns', '0005_auto_20170919_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winningbillboardmedia',
            name='billboardMedia',
        ),
        migrations.RemoveField(
            model_name='winningbillboardmedia',
            name='billboard_ptr',
        ),
        migrations.AddField(
            model_name='billboardmedia',
            name='ABWinner',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WinningBillboardMedia',
        ),
    ]
