# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 23:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last', models.CharField(max_length=150)),
                ('dept', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(max_length=2500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confirmed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Company')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(to='directory.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('email', 'company')]),
        ),
    ]
