# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
    ]
