# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('full_user', 'Can CRUD other full users.'), ('half_user', 'Can CRUD itself.'))},
        ),
    ]
