# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170920_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=3, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(default=33, max_length=2500, unique=True),
            preserve_default=False,
        ),
    ]
