# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_user_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, to='directory.Group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
