# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20170911_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=200),
        ),
    ]
